### ISSUE TITLE
Random Item scenario uses old registers

### ISSUE THREAD

**Issue by ghost** [DeflatedPickle/Colony#49]
So when I start the debug Random Items Scenario it out puts this text into the console.
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Xavie.DESKTOP-TFJ01Q7\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "C:\Users\Xavie.DESKTOP-TFJ01Q7\Desktop\Colony-master\scenarios.py", line 156, in start_game
    self.spawn(self.scenario_list[self.selected_scenario])
  File "C:\Users\Xavie.DESKTOP-TFJ01Q7\Desktop\Colony-master\scenarios.py", line 198, in spawn
    reg_item = self.game.register_items()[random.choice(list(self.game.register_items().keys()))]
TypeError: 'dict' object is not callable`
I am using python 3.5 and I am going to try it on python 3.0.1.

**Comment by DeflatedPickle** [comment]
Awhile ago, all registers were moved from functions to dictionaries. This scenario was never updated to comply with the update.
